drop table if exists assignee_domain CASCADE;
drop table if exists task_domain CASCADE;
create table assignee_domain (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table task_domain (id bigint generated by default as identity, completed boolean not null, date_time_set timestamp not null, title varchar(255) not null, primary key (id));